### ISSUE TITLE
Anchor tags should not be used for non-navigation buttons

### ISSUE THREAD

**Issue by shailpatels** [Submitty/Submitty#7819]
**Describe the bug**
A number of places throughout Submitty use anchor tags and are stylized as buttons but do not perform navigation and instead rely on an `onclick` event. This can confuse screen readers which might interpret the element as a link. Browsers may also fire events differently based on if an element is an anchor tag or a `button`

**Expected behavior**
Elements that perform an action and do not change the page should use the `button` tag, the `button` tag also automatically fires `onclick` when pressed via keyboard which would remove the use of the `key_to_click` class being used everywhere 

**Additional context**
https://css-tricks.com/buttons-vs-links/
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#onclick_events

**Comment by immortalcodes** [comment]
@shailpatels I have read previous commits & comments . I am looking for more places where anchor tags could be corrected with button tag, as described in issue. Could you please suggest some files to narrow down my search.

**Comment by shailpatels** [comment]
@immortalcodes you can search for anchor tags that are using the `onclick` attribute along with the class `key_to_click` these are a good way of telling if a link is being used in an area it's not supposed to.

There's no way to automatically find files with the issue so you would have to manually search through files and see if their usage in the application is correct or wrong manually unfortunately.

**Comment by immortalcodes** [comment]
@shailpatels 
[onclick.txt](https://github.com/Submitty/Submitty/files/8693781/onclick.txt)

I made script to filter out all the lines in codebase that contained anchor tag with onclick event along with their exact location. This should make work easier for anyone working on the issue.

I am working on correcting them.

**Comment by poorna2152** [comment]
When changing `<a>` tags with the css classes `btn`, `btn-default` to `<button>` tag  seem to mess up the styling
![Screenshot from 2022-05-24 19-36-39](https://user-images.githubusercontent.com/58025190/170066414-f3bd5caa-b990-49b1-9489-a82b72f24507.png)
The button in the middle is changed from `<a>` to `<button>`. It is supposed to have the same styling as the other two.

**Comment by williamjallen** [comment]
#7863 addresses some of the problems but doesn't fix all of them so I'm going to re-open this issue.

**Comment by charvimehradu** [comment]
Please review the above mentioned PR and let me know if any changes are required

**Comment by micpap25** [comment]
Per Shail, it's a good idea to remove the `key_to_click` class from `<button>`s. I'll make a PR to do this.
